### ISSUE TITLE
Output plugins

### ISSUE THREAD

**Issue by mattaezell** [chenglch/goconserver#14]
It appears that `goconserver` currently only supports writing to flat files.  It would be nice if I could specify an alternate output plugin, to write structured data directly to `rsyslog` or `logstash`.

**Comment by chenglch** [comment]
Hi @mattaezell , Does the design below meet your requirement ? 

/etc/goconserver/server.conf
```
……
console:
  # the logger type for the console output, could be file_logger, tcp_logger or udp_logger.
  logger_type: tcp_logger
  # only available when the logger is set to file_logger
  file_logger:
    # the log files directory for session nodes.
    logdir: /var/log/goconserver/nodes/

  tcp_logger:
    address: 127.0.0.1:9563
    timeout: 5
    # If ssl is not set, use tcp connection directly.

    # ssl_key_file: /etc/goconserver/cert/server-cred.pem
    # ssl_cert_file: /etc/goconserver/cert/server-cred.pem
    # ssl_ca_cert_file: /etc/goconserver/cert/ca.pem

    # if true, do not verify the certificate from server side.

    # ssl_insecure: true

  udp_logger:
    address: 127.0.0.1:9563
    timeout: 5

  # log the timestamp.
  log_timestamp: true
```
The configuration for `logstash`
```
input {
  tcp {
    #codec => json
    port => '9563'
    #ssl_extra_chain_certs =>   # cacert
    # ssl_cert
    #ssl_enable
    # ssl_key
    # ssl_verify
  }
}

output {
  stdout {
    #codec => json_lines
  }
}
```

Below is an example output from `logstash`, as `logstash` contains the `timestamp` field, the `date` field from the json output could be disabled by the `log_timestamp` setting in the `/etc/goconserver/server.conf`.
Currently only two message type: `event` and `console`. 
```
2018-01-05T07:55:06.227Z localhost {"date":"2018-01-05 15:55:05.9724","message":"-bash-4.1$ \r","node":"bulknode2","type":"console"}
2018-01-05T07:55:16.223Z localhost {"date":"2018-01-05 15:55:15.8386","message":"/u/chenglch\r","node":"bulknode2","type":"console"}
2018-01-05T07:55:16.222Z localhost {"date":"2018-01-05 15:55:15.8385","message":"-bash-4.1$ pwd\r","node":"bulknode2","type":"console"}
2018-01-05T07:55:20.221Z localhost {"data":"2018-01-05 15:55:19.7343","message":"[goconserver disconnected]","node":"bulknode2","type":"event"}
```

**Comment by mattaezell** [comment]
Hi @chenglch, this looks good.  For `file_logger`, the node name is embedded in the output filename.  For tcp and udp, how are the messages framed on the wire?  JSON?  Plaintext?  Is it configurable?

I also wonder if it makes sense to allow multiple output plugins, or if that should be handled by whatever is listening (both rsyslog and logstash support multiple outputs)?

**Comment by chenglch** [comment]
@mattaezell , for tcp and udp, the message format would be json, like below:
```
{"date": "2018-01-05 15:55:05.9724",  # could be disabled
 "message": console log line like "-bash-4.1$ pwd\r" or the event prompt like "[goconserver disconnected]"  ,
 "type" :  event or console, 
 "node": <node name>
}
```
 
For the output plugins, maybe your requirement is to redirect the console message to multiple targets, so the configuration would be designed like:
```
console:
  .....
  logger:
    file:
      - logdir: /var/log/goconserver/nodes/
    tcp:
      - host: 127.0.0.1
        port: 9563
        timeout: 5
        # If ssl is not set, use tcp connection directly.

        # ssl_key_file: /etc/goconserver/cert/server-cred.pem
        # ssl_cert_file: /etc/goconserver/cert/server-cred.pem
        # ssl_ca_cert_file: /etc/goconserver/cert/ca.pem

        # if true, do not verify the certificate from server side.

        # ssl_insecure: true
      - host: x.x.x.x
        port: 9563
    udp:
      - host: 127.0.0.1
      - port: 9563
      - timeout: 5

  # log the timestamp.
  log_timestamp: true
```
